[package]
name = "snatch"
version = "0.1.0"
authors = ["Antonin Carette <antonin@derniercri.io", "Jean-Serge Monbailly <jean-serge@derniercri.io>"]

[dependencies]
hyper = "0.9"
libsnatch = { git = "ssh://github.com/derniercri/libsnatch.git" }